class Logger
  def initialize: (untyped) -> void
  def info: (String) -> void
  def warn: (String) -> void
  def error: (String) -> void
  def debug: (String) -> void
end

module RSpec
  def self.configure: () { (untyped) -> void } -> void
end

module Minitest
  def self.after_run: () { () -> void } -> void
end

module Rails
  class Railtie
    def self.initializer: (String, ?untyped) { (untyped) -> void } -> void
  end

  class Engine < Railtie
  end

  module Application
  end

  def self.env: () -> ActiveSupport::StringInquirer
  def self.root: () -> Pathname

  class Configuration
  end
end

module ActiveSupport
  class StringInquirer < String
    def development?: () -> bool
    def test?: () -> bool
    def production?: () -> bool
  end
end

module Bullet
  class BulletRailtie
    def self.initializers: () -> Array[untyped]
  end

  class Rack
  end

  def self.enable?: () -> bool
  def self.start_request: () -> void
  def self.end_request: () -> void
  def self.notification?: () -> bool

  module Notification
    class NPlusOneQuery
      attr_reader base_class: untyped
      attr_reader associations: untyped

      def initialize: (untyped, untyped, ?untyped?) -> void
    end

    class UnusedEagerLoading
      attr_reader base_class: untyped
      attr_reader associations: untyped
    end
  end

  module Detector
    module Association
    end
  end
end

class Prism::CallNode
  def block: () -> untyped
  def receiver: () -> untyped
  def name: () -> Symbol
  def arguments: () -> untyped
  def location: () -> untyped
end

class Prism::ConstantReadNode
  def name: () -> Symbol
  def full_name: () -> String
  def location: () -> untyped
end

class Prism::ConstantPathNode
  def full_name: () -> String
  def location: () -> untyped
end

class Prism::InstanceVariableWriteNode
  def name: () -> Symbol
  def value: () -> untyped
  def location: () -> untyped
end

class Prism::LocalVariableWriteNode
  def name: () -> Symbol
  def value: () -> untyped
  def location: () -> untyped
end

class Prism::InstanceVariableReadNode
  def name: () -> Symbol
  def location: () -> untyped
end

class Prism::LocalVariableReadNode
  def name: () -> Symbol
  def location: () -> untyped
end

class Prism::SymbolNode
  def value: () -> String
end

class Prism::ArrayNode
  def elements: () -> Array[untyped]
end

class Prism::KeywordHashNode
  def elements: () -> Array[untyped]
end

class Prism::HashNode
  def elements: () -> Array[untyped]
end

class Prism::AssocNode
  def key: () -> untyped
  def value: () -> untyped
end

class Prism::DefNode
  def name: () -> Symbol
  def body: () -> untyped
  def location: () -> untyped
end

module Prism
  def self.parse: (String, ?filepath: String?) -> untyped
  def self.parse_file: (String) -> untyped
end
